name: JSON check

on:
  push:
    paths:
      - '**.json'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"
      - name: Validate appsettings.json
        uses: docker://orrosenblatt/validate-json-action:latest
        with:
          INPUT_SCHEMA: ./appsettings.schema.json
          INPUT_JSONS: ./appsettings.json
      - name: Validate countries.json
        uses: docker://orrosenblatt/validate-json-action:latest
        with:
          INPUT_SCHEMA: ./countries.schema.json
          INPUT_JSONS: ./countries.json